# Generated by Django 4.1 on 2022-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=12)),
                (
                    "path",
                    models.CharField(
                        choices=[
                            ("AWS", "AWSDevOps"),
                            ("FS", "FullStack"),
                            ("DS", "DataScience"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
